### ISSUE TITLE
Cannot install the extension

### ISSUE THREAD

**Issue by Darkk3n** [wsr-publishing/azure-poor-formatter#1]
Hello,

I'm using the latest version of Azure Data Studio and tried to install this extension but everytime I try I get the following error message:

![image](https://user-images.githubusercontent.com/5014837/57965074-ceed5080-7904-11e9-88e8-07eb79f8edf0.png)

I looked at the install log and noticed these lines:

_5/18/2019 12:33:17 AM - Searching for applicable products...
5/18/2019 12:33:17 AM - Found installed product - Global Location
5/18/2019 12:33:17 AM - Found installed product - Visual Studio Community 2019_

I'd appreciate a hand with this, I'm not sure if my Azure Data Studio has a problem or something

Thank you in advance

**Comment by dannyrich** [comment]
This worked for me to install:

1. Go to the Extension tab:

![image](https://user-images.githubusercontent.com/2489135/58038507-fbf85980-7ae4-11e9-95a3-cd6a7a1e8435.png)

2. Open the extension menu and choose `Install From VSIX...`:

![image](https://user-images.githubusercontent.com/2489135/58038600-29450780-7ae5-11e9-89b0-582908f5de62.png)

3. Choose the VSIX that you downloaded from the [releases](https://github.com/wsr-publishing/azure-poor-formatter/releases) page.

Let me know if that worked for you.
