### ISSUE TITLE
How does this get called?

### ISSUE THREAD

**Issue by end-user** [wsr-publishing/azure-poor-formatter#3]
I installed it, but I don't know how to run it.  I can right-click the page and "format with", but this isn't an option that appears under the format providers.

**Comment by dannyrich** [comment]
Open the Command Palette (View > Command Palette...) then type `Poor SQL`. Then choose either "format" or "obfuscate". You can get to the settings by going to the Extensions view and clicking the gear icon next to Poor SQL Formatter.

**Comment by UgmaDevelopment** [comment]
I came here with the same question. Thanks for having an answer!

I wonder if there's a way to make it work similarly to Visual Studio's traditional formatter.

**Comment by UgmaDevelopment** [comment]
Here's how we could make it a formatter extension: 
https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices

Anyone else interested?
