### ISSUE TITLE
I can't install this extension

### ISSUE THREAD

**Issue by CatalinRadoi** [wsr-publishing/azure-poor-formatter#4]
I have both azure data studio and visual studio code.

I wanted to install this in azure data studio... but I can't

![can't install](https://user-images.githubusercontent.com/12814553/97104480-e1a0b300-16bc-11eb-83c7-6c12b771ce71.PNG)

**Comment by CatalinRadoi** [comment]
Ok, because I have both Visual Studio and Visual Studio Code installed, the Visual Studio selector gets confused.

I was able to install the extension by **manually dragging it to Azure Data Studio.**

**Comment by UgmaDevelopment** [comment]
I ran into this same issue: it wouldn't install.

And when I dried dragging it into Azure Data Studio it didn't work, either.

However, I _was_ able to install it by going to File → Install Extension from VSIX Package

![image](https://user-images.githubusercontent.com/19827042/106020825-62d36180-6081-11eb-8632-b7aa9b4ab6ec.png)

Thanks!
