### ISSUE TITLE
Format create table

### ISSUE THREAD

**Issue by dimanrus** [wsr-publishing/azure-poor-formatter#9]
Hello. I have a code.
![image](https://github.com/wsr-publishing/azure-poor-formatter/assets/41239551/1eefd4e7-0090-4850-92a4-f3a4a1e72260)
I want to get the next result.
![image](https://github.com/wsr-publishing/azure-poor-formatter/assets/41239551/84541cd1-cf54-4cd2-ac5e-88a8edc17010)

**Comment by tamasys** [comment]
Hi @DIMANRUS, you can do this by changing the `Trailing Commas` option in the [Extension Settings](https://learn.microsoft.com/en-us/azure-data-studio/settings):
![image](https://github.com/wsr-publishing/azure-poor-formatter/assets/2321397/1b0bf472-8096-490a-9c9d-090fcddea393)

**Comment by dimanrus** [comment]
> Hi @DIMANRUS, you can do this by changing the `Trailing Commas` option in the [Extension Settings](https://learn.microsoft.com/en-us/azure-data-studio/settings):
> ![image](https://github.com/wsr-publishing/azure-poor-formatter/assets/2321397/1b0bf472-8096-490a-9c9d-090fcddea393)
> 

Thanks
